version: '3'
services:
  web:
    build: .
    container_name: django_laboratorious-campuss
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: uea_news.settings
      DB_NAME: laboratorio_local
      DB_USER: laboratorio_local
      DB_PASSWORD: tcc123
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - django_network

  db:
    image: postgres:13
    container_name: postgres_laboratorious-campus
    restart: always
    environment:
      POSTGRES_DB: laboratorio_local
      POSTGRES_USER: laboratorio_local
      POSTGRES_PASSWORD: tcc123
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_laboratorious-campus
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - django_network

volumes:
  pg_data:

networks:
  django_network: