# Generated by Django 4.1.3 on 2025-04-23 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_ajustavel', models.TextField(verbose_name='Texto Para Tela Principal')),
            ],
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=255, verbose_name='nome do equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoDePesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_grupo', models.CharField(max_length=255, null=True, verbose_name='Nome do grupo de pesquisa')),
                ('area', models.CharField(max_length=50, null=True, verbose_name='Área de atuação')),
                ('link_grupo', models.URLField(blank=True, null=True, verbose_name='Link do grupo de pesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(null=True, upload_to='imagens_laboratorio/', verbose_name='Imagem do Laboratório')),
                ('data_upload', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Infraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, null=True, verbose_name='modelo do equipamento')),
                ('finalidade', models.CharField(max_length=1000, null=True, verbose_name='finalidade do equipamento')),
                ('status', models.BooleanField(default=True)),
                ('tombo', models.CharField(default='-', max_length=300, null=True, verbose_name='tombo')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infraestrutura_equipamento', to='core.equipamento', verbose_name='Nome do Equipamento lista')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_laboratorio', models.CharField(max_length=255, verbose_name='nome do laboratorio')),
                ('responsavel', models.CharField(default='jose carlos', max_length=255, verbose_name='Usuário de cadastro')),
                ('cpf_responsavel', models.CharField(blank=True, max_length=14, null=True)),
                ('user_ldap_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(default='meu_email@example.com', max_length=254, verbose_name='email')),
                ('telefone', models.CharField(default='9299999', max_length=15, verbose_name='numero de telefone')),
                ('unidade', models.CharField(default='meu_email', max_length=255, null=True, verbose_name='unidade academica')),
                ('rua', models.CharField(default='meu_email@example.com', max_length=255, null=True, verbose_name='nome da rua do laboratorio')),
                ('numero_rua', models.PositiveIntegerField(default='32232', null=True, verbose_name='numero da rua do laboratorio')),
                ('cep', models.PositiveIntegerField(default='33323', null=True, verbose_name='cep do bairro do laboratorio')),
                ('bairro', models.CharField(default='jose carlos', max_length=255, null=True, verbose_name='nome do bairro do laboratorio')),
                ('andar', models.CharField(blank=True, max_length=255, null=True)),
                ('sala', models.CharField(max_length=20, null=True, verbose_name='sala do laboratorio')),
                ('funcionamento', models.CharField(max_length=255, null=True, verbose_name='nome do local de funcionamento do laboratorio')),
                ('descricao', models.TextField(default='ou', max_length=400, null=True, verbose_name='descricao das atividades de pesquisa e ensino:')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site do laboratório')),
                ('link_pnipe', models.CharField(default='ou', max_length=255, null=True, verbose_name='link do pnipe')),
                ('ato_anexo', models.BinaryField(blank=True, null=True, verbose_name='Anexo do Ato')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('ocultar_laboratorio', models.BooleanField(default=False, verbose_name='Ocultar laboratório')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('grupos_de_pesquisa', models.ManyToManyField(blank=True, related_name='laboratorios', to='core.grupodepesquisa')),
                ('imagens', models.ManyToManyField(blank=True, related_name='laboratorios_lab', to='core.imagemlaboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=100, verbose_name='nome da marca do equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(default='Padrão', max_length=100, verbose_name='Setor do usuário')),
            ],
            options={
                'db_table': 'unidade',
            },
        ),
        migrations.CreateModel(
            name='UnidadeAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf_unidades_academicas/')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_academicas_do_laboratorio', to='core.laboratorio')),
            ],
            options={
                'db_table': 'unidade_academica',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Responsável Associado')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF do Responsável Associado')),
                ('user_ldap', models.CharField(blank=True, max_length=255, null=True, verbose_name='USER_LDAP do Responsável Associado')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis_associados', to='core.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='RegimentoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdf_regimentos_internos/')),
                ('nome_do_pdf', models.CharField(default='pedro', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimentos_internos', to='core.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=255)),
                ('nome_projeto', models.CharField(max_length=255)),
                ('docente_responsavel', models.CharField(max_length=255)),
                ('modalidade', models.CharField(max_length=100)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('fomento', models.CharField(max_length=100)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_lab', to='core.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_Programa', models.CharField(max_length=255, null=True, verbose_name='nome pos')),
                ('website', models.URLField(blank=True, null=True, verbose_name='link para o site')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='core.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='MembroLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_membro', models.CharField(max_length=80, null=True, verbose_name='nome do membro')),
                ('funcao', models.CharField(max_length=100, null=True, verbose_name='função')),
                ('curriculo_lattes', models.URLField(null=True, verbose_name='currículo Lattes')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100)),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discente')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratorioInfraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infraestrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.infraestrutura')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infraestruturas', to='core.laboratorio')),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='unidades_academicas',
            field=models.ManyToManyField(blank=True, related_name='laboratorios', to='core.unidadeacademica'),
        ),
        migrations.AddField(
            model_name='infraestrutura',
            name='laboratorio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.laboratorio'),
        ),
        migrations.AddField(
            model_name='infraestrutura',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infraestrutura_marca', to='core.marca', verbose_name='Nome da Marca lista'),
        ),
        migrations.AddField(
            model_name='imagemlaboratorio',
            name='laboratorios',
            field=models.ManyToManyField(blank=True, related_name='imagens_lab', to='core.laboratorio'),
        ),
        migrations.CreateModel(
            name='ImagemInfraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='infraestrutura_images/', verbose_name='Imagem da Infraestrutura')),
                ('infraestrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_infraestrutura', to='core.infraestrutura', verbose_name='Infraestrutura')),
            ],
        ),
        migrations.CreateModel(
            name='Formento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedoparceito', models.CharField(max_length=255, null=True, verbose_name='nome do formento')),
                ('selecao', models.CharField(max_length=255, null=True, verbose_name='selecao do formento')),
                ('tipo', models.CharField(max_length=30, null=True, verbose_name='fomento ou parceiria')),
                ('edital', models.CharField(max_length=255, null=True, verbose_name='nome do edital')),
                ('numerodoformento', models.IntegerField(null=True, verbose_name='numero do edital')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formentos', to='core.laboratorio')),
            ],
        ),
        migrations.AddField(
            model_name='discente',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discentes', to='core.projeto'),
        ),
    ]
